Makefile

It outputs an error if the submodules aren't checked out.

Check for submodules in makefile

---

ndless-sdk/include/libndls.h
ndless-sdk/libndls/show_msg_user_input.c

The defaultvalue parameter is now const char*, which allows using a string literal in C++.
I also added the strdup failure check.

More changes to show_msg_user_input

---

ndless-sdk/thirdparty/Makefile

I was relying on the behavior of GNU head, and that wouldn't have worked on Mac OS X or OpenBSD, at least. This should fix #44 by using sed instead. Somebody should test this before it is merged, because I don't have access to a Mac OS X system.

To determine CHOST, use sed instead of head for portablity

---

ndless-sdk/toolchain/build_toolchain.sh

Tested with the 4.4 installer, works fine.
(Also remove trailing whitespaces from the script)

toolchain: update GCC to 6.3.0

---

ndless-sdk/toolchain/build_toolchain.sh

And align some things here and there...

toolchain: fix bracket-depth gcc build error when using clang

---

README.md

Fixed a typo in `Legal stuff`
> read careful **ly**
…
> before distributing **[…]** any part

Fix Typo in README.MD

---

ndless-sdk/toolchain/build_toolchain.sh

Without the quotes, running ./build_toolchain in WSL will return a parsing error due to the space in the name of the "Program Files" directory.

Fix build issues in WSL

---

ndless-sdk/include/hook.h

**Disclaimer**: I haven't checked the rest of the file for typos. If you find any, feel free to suggest changes.
I'm not fully sure whether I understand this comment correctly and whether we need the `They`. However, `must always exit` stays the same no matter whether it's `it must exit` or `they must exit`.
Changed:
* Fixed indention of block comment
* Changed "Must exits" -> "They must exit"

Fix typo in hooks.h

---

ndless-sdk/toolchain/build_toolchain.sh

The previous version, GDB 8.0, has problems with Python 3.7. https://bugzilla.redhat.com/show_bug.cgi?id=1577396

Switch to GDB 8.1.1

---

ndless-sdk/libndls/config.c
ndless/src/resources/install.c

Do it explicitly on startup so it can find the file even if the documents dir
changes.
Fixes #138
@pbfy0 This will conflict with your PR, which also caches the cfg path (but in a different function).
Binary for testing:
[ndless_resources.zip](https://github.com/ndless-nspire/Ndless/files/2441441/ndless_resources.zip)

Cache the path were ndless.cfg.tns was last found

---

ndless-sdk/toolchain/build_toolchain.sh

Many modern systems have 8+ cores and could build the toolchain much faster without the need to manually configure the build script.
If I got something essentially wrong, please let me know.

toolchain: use nproc for build script

---

ndless-sdk/Dockerfile.arm-gcc
ndless-sdk/Dockerfile.ndless-sdk

This PR fixes Docker by adding the required `xz-utils` dependency and a call to `make` in the `/ndless-sdk` folder.
If this is merged, I request that the Docker images on Dockerhub are updated as well. This should fix #93.

Fix Dockerfiles

---

ndless-sdk/toolchain/build_toolchain.sh

newlib may have broken ABI so let's not update that for now just in case.
This builds fine (well, better) on macOS than before because of some isl dependency issue ( https://github.com/kendryte/kendryte-gcc/commit/5b254d7c602ec112161daa0981e1b9ace1052c47 )

build_toolchain: update binutils, gcc, gdb

---

ndless-sdk/include/syscall-list.h
ndless-sdk/libsyscalls/mkStubs.php
ndless-sdk/libsyscalls/stubs.cpp

- It didn't match parameters with parentheses in their declaration correctly,
leading to the wrong number of arguments being parsed
- Made the regex nongreedy and match line start and end explicitly to fix this
- Fix syscall declarations with whitespace at the end
Fixes #193

Fix parsing of some syscall parameters

---

ndless-sdk/libndls/config.c

Got broken in #64 and might've caused the reports about nPDF not working properly.

Fix cfg_register_fileext if ndless.cfg.tns doesn't exist yet

---

ndless-sdk/toolchain/build_toolchain.sh

This caused a different set of headers to be used.
AFAICT this isn't actually quite how it's meant to work, as this copies over the non-arch specific headers to a path with higher priority. It would require upgrading newlib with a version that doesn't have an incomplete `param.h` for arm or deleting that file manually, but the hack to delete `sys-include/newlib.h` would not be needed anymore.
For now let's just keep the status quo to avoid more surprises.
Fixes #216

build_toolchain.sh: Fix path in gcc configure options

---

ndless-sdk/bin/arm-none-eabi-ld.gold
ndless-sdk/bin/nspire-as
ndless-sdk/bin/nspire-g++
ndless-sdk/bin/nspire-gcc

This allows to not link every single `arm-none-eabi-*` executable into usr/bin in my AUR package, which will reduce conflicts with e.g. arm-none-eabi-binutils

Put _toolchainpath in PATH in nspire-* scripts

---

.github/workflows/main.yml

My original motivation for this was to let you provide "nightly" builds of the SDK and toolchain, so our CI would not have to duplicate effort, but it seems that GitHub Actions does not let you easily download artifacts from other repositories (yet?).
Still, the effort was made, so here's a free CI workflow for your project! :)
On runtimes:
- The toolchain takes roughly 40 minutes to build. Caching is implemented, and a rebuild is triggered whenever the `build-toolchain.sh` script changes (because it contains the gcc, binutils, etc version numbers used to build the toolchain). Unfortunately, jobs can't access past run's artifacts, so that has to uploaded on every run, adding ~2 min of runtime :/ A possible (but less clean) solution would be to merge the two jobs into one.
- Caching does …

Github Actions workflow for building the toolchain and the SDK

---

ndless/src/installer-4.5/Makefile

Mostly untested. Assumes the following have been installed with brew:
- binutils
- boost
- gcc
- git
- gmp
- libmpc
- mpfr
- wget
- zlib
May break if more than one gcc version is installed.

Fix ndless_installer_4.5 on macOS

---

ndless-sdk/libsyscalls/stdlib.cpp
ndless-sdk/system/crt0.S
ndless-sdk/system/crtn.S

Smaller binaries, less memory leaks.

Some newlib-related optimizations

---

ndless-sdk/bin/nspire-g++

Using the atexit mechanism for static object destruction is the only way to
ensure that it's correctly ordered as required by the standard. This way
they also run when calling exit instead of returning from main.

Switch to using cxa_atexit for static destruction

---

ndless-sdk/include/nucleus.h
ndless-sdk/libsyscalls/stdlib.cpp
ndless-sdk/samples/luaext/luaextdemo.c

In some circumstances, it's important to skip cleanup on exit, like in the case
of crash handlers and especially for resident programs.
Make luaextdemo use that feature.
See #287

Only perform cleanup when exiting cleanly

---

.github/workflows/main.yml

Compile with all cores to speed it up and adjust it to the host
Upload the Build Artifacts so they can be testet easier

Compile with all cores and upload the Build Artifacts

---

.github/workflows/main.yml
ndless-sdk/libsyscalls/stdlib.cpp
ndless-sdk/samples/zehn/test.cpp
ndless-sdk/system/crti.S
ndless-sdk/system/crtn.S
ndless-sdk/system/ldscript
ndless-sdk/toolchain/build_toolchain.sh

- binutils 2.44
- GCC 14.2.0
- newlib 4.5.0
- GDB 16.2
Might need nSDL rebuilt, could also drop `--enable-newlib-reent-binary-compat` then.
For some reason, the `newlib-c++` sample pulls in arc4random which requires `_getentropy` and is massive. Needs investigation why.

Toolchain update

---

ndless-sdk/libsyscalls/stdlib.cpp
ndless-sdk/tools/zehn_loader/Makefile

* libsyscalls: Make sure never to allocate 0-2 as FDs
* libsyscalls: Properly return failure if open with O_CREAT fails
* + some zehn_loader fix that was lying around.

libsyscalls: Some FD related fixes

---

ndless/src/resources/install.c
ndless/src/resources/ploaderhook.c
ndless/src/resources/utils.c

* Fix that the cursor was sometimes visible in lcd_compat mode
* Fix for an OS bug that hid the leftmost LCD column on CX II
* Update Luna
* Use the watchdog as fallback reset method to make `ut_calc_reboot` work on CX II
Contributions from @satyamedh

CX II LCD fixes + Luna update 
